name: electron-setup
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: http://registry.npmmirror.com
     
      - name: Setup Pnpm
        run: npm i -g pnpm
     
      - name: Install Pnpm
        run: pnpm run bootstrap
        
      - name: Build
        run: pnpm run electron:build
        
      - name: Upload File
        uses: actions/upload-artifact@v3 
        with:
          name: jingluo-window
          path: dist_electron/*.*
