name: electron-setup
on:
  workflow_dispatch:
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Build
        run: pnpm run electron:build
