name: electron-setup
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: build and release electron app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.com/

      - name: Setup Pnpm
        run: npm i -g pnpm
        
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
          
     # - uses: actions/cache@v3
      #  name: Setup pnpm cache
      #  with:
        #  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
         # key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
         # restore-keys: |
           # ${{ runner.os }}-pnpm-store-
            
      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run electron:build
        env:
          GH_TOKEN: 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
         
      - name: Clean Upload File
        run: |
          pnpm rimraf "dist_electron/!(*.exe|)"

      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: window
          path: dist_electron

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist_electron/**"
        env:
          GH_TOKEN: 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
          GITHUB_TOKEN: ${{ secrets.PRESS_TOKEN }}
