name: electron-setup
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: http://registry.npmmirror.com
      - name: Pnpm Setup
        run: npm i -g pnpm
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Build
        run: pnpm run electron:build
