name: node-setup
on:
  push:
    # 分支随意
    branches:
      - master
jobs:
  install:
    # runs-on字段指定运行所需要的虚拟机环境。它是必填字段。目前可用的虚拟机如下。
    runs-on: ubuntu-latest
    steps:
      - name: setup-node
        #使用setup-node@v1这个action
        uses: actions/setup-node@v3
        #指定某个action 可能需要输入的参数
        with:
          node-version: 16
