name: ssh-setup
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: ssh and release electron 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Deploy   都采用secrets加密防止外泄
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.SSH_ACCESS_TOKEN }}
          # scp参数
          ARGS: "-avz --delete"
          # 源目录，编译后生成的文件目录
          SOURCE: "./"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          # 用户
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
           # 目标地址 你在服务器上部署代码的地方
          TARGET: ${{ secrets.SSH_TARGET }}

          EXCLUDE: "/dist/, /node_modules/, /dist_electron/"

      - name: Check build product
        run: sh -c ./scripts/publish.sh

